//
//  IDEWorkspace.h
//  IDEFoundation
//
//  Created by Roman Dzieciol on 4/6/19.
//  Copyright © 2019 Roman Dzieciol. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <RDIDEFoundation/RDIDEFoundationDecls.h>

NS_ASSUME_NONNULL_BEGIN


@interface IDEWorkspace : NSObject {
    NSString * _untitledName;
    IDEWorkspaceArena * _workspaceArena;
    DVTFilePath * _headerMapFilePath;
    IDEExecutionEnvironment * _executionEnvironment;
    IDEContainerQuery * _containerQuery;
    DVTObservingToken * _containerQueryObservingToken;
    NSMutableSet * _referencedContainers;
    NSHashTable * _fileRefsWithContainerLoadingIssues;
    IDEActivityLogSection * _containerLoadingIntegrityLog;
    NSMutableSet * _customDataStores;
    IDEWorkspaceUserSettings * _userSettings;
    IDEWorkspaceSharedSettings * _sharedSettings;
    NSMapTable * _blueprintProviderObserverMap;
    NSMapTable * _blueprintProviderEditedObserverMap;
    NSMutableSet * _referencedBlueprints;
    char _initialContainerScanComplete;
    NSMutableArray * _referencedRunnableBuildableProducts;
    IDERunContextManager * _runContextManager;
    IDELogManager * _logManager;
    IDEIssueManager * _issueManager;
    IDEBreakpointManager * _breakpointManager;
    IDETestManager * _testManager;
    _TtC16DVTDocumentation23DVTDocumentationManager * _documentationManager;
    IDEContainerQuery * _indexableSourceQuery;
    DVTObservingToken * _indexableSourceQueryObservingToken;
    NSMapTable * _observedIndexableSourcesToObservingTokensTable;
    IDEIndex * _index;
    NSMapTable * _identifiersToIndexablesPendingRegistration;
    DVTTimeSlicedMainThreadWorkQueue * _indexRegistrationQueue;
    IDEDeviceInstallWorkspaceMonitor * _deviceInstallWorkspaceMonitor;
    IDEProvisioningWorkspaceMonitor * _provisioningWorkspaceMonitor;
    IDESourceControlWorkspaceMonitor * _sourceControlWorkspaceMonitor;
    IDEProvisioningManager * _provisioningManager;
    IDELocalizationManager * _localizationManager;
    _TtC13IDEFoundation30IDEStructureEditingCoordinator * _structureEditingMoveCoordinator;
    NSNumber * _shouldUseLegacyBuildSystem;
    NSObject<IDEBuildSystemServiceProvider> * _buildSystemServiceProvider;
    DVTNotificationToken * _buildSystemSettingsNotificationToken;
    DVTFilePath * _wrappedContainerPath;
    IDEContainer<IDECustomDataStoring> * _wrappedContainer;
    DVTObservingToken * _wrappedContainerValidObservingToken;
    DVTObservingToken * _newWrappedContainerObservingToken;
    NSHashTable * _pendingReferencedFileReferences;
    NSHashTable * _pendingReferencedContainers;
    DVTNotificationToken * _holdFilesOnAppActivationNotificationToken;
    IDEConcreteClientTracker * _clientTracker;
    NSHashTable * _fileReferencesForProblem8727051;
    DVTObservingToken * _finishedLoadingObservingToken;
    NSDictionary * _Problem9887530_preferredStructurePaths;
    char _simpleFilesFocused;
    id _openingPerformanceMetricIdentifier;
    DVTStackBacktrace * _finishedLoadingBacktrace;
    NSMutableOrderedSet * _initialOrderedReferencedBlueprintProviders;
    char _hasPostedIndexingRegistrationBatchNotification;
    char _didFinishLoadingFirstStage;
    char _finishedLoading;
    char _postLoadingPerformanceMetricsAllowed;
    char _willInvalidate;
    char _pendingFileReferencesAndContainers;
    char _didProcessFileReferencesForProblem8727051;
    char _isCleaningBuildFolder;
    char _indexingAndRefactoringRestartScheduled;
    char _indexCreationInFlight;
    char _didFinishBuildingInitialBlueprintProviderOrderedSet;
    NSMapTable * _pendingExecutionNotificationTokens;
    char _isWaitingForSourcePackages;
    char _wasLoadedForUIContext;
    char _hostsOnlyWrappedContainer;
    char _hostsOnlyXcode3Project;
    char _hostsOnlyPackages;
    char _hostsOnlyPlayground;
    char _isPotentiallyClosing;
    IDEDynamicContentRootGroup * _dynamicContentRootGroup;
    NSArray * _sourcePackageLoadingErrors;
    IDEActivityLogSection * _sourcePackageResolutionIssueLog;
    IDETextFragmentIndex * _textFragmentIndex;
    IDERefactoring * _refactoring;
    IDEWorkspaceUpgradeTasksController * _deferredUpgradeTasksController;
    NSDate * _icloudDriveLastHeldDate;
    NSObject<IDEActiveRunContextStoring> * _activeRunContextStore;
}
@property (retain) NSArray * namedBatchFindScopes;
@property (retain,nonatomic) IDEWorkspaceArena * workspaceArena;
@property (retain) IDEDynamicContentRootGroup * dynamicContentRootGroup;
@property (retain) IDEDeviceInstallWorkspaceMonitor * deviceInstallWorkspaceMonitor;
@property (retain) IDEProvisioningWorkspaceMonitor * provisioningWorkspaceMonitor;
@property (retain) IDESourceControlWorkspaceMonitor * sourceControlWorkspaceMonitor;
@property (retain) IDEIndex * index;
@property char initialContainerScanComplete;
@property (nonatomic) char finishedLoading;
@property (nonatomic) char pendingFileReferencesAndContainers;
@property (readonly) IDEConcreteClientTracker * clientTracker;
@property (retain) IDERunContextManager * runContextManager;
@property (retain) IDEExecutionEnvironment * executionEnvironment;
@property (retain) IDEBreakpointManager * breakpointManager;
@property (retain,nonatomic) IDEWorkspaceUserSettings * userSettings;
@property (retain,nonatomic) IDEWorkspaceSharedSettings * sharedSettings;
@property (retain) IDETestManager * testManager;
@property (retain,nonatomic) IDEProvisioningManager * provisioningManager;
@property (retain) _TtC16DVTDocumentation23DVTDocumentationManager * documentationManager;
@property (retain) IDEWorkspaceUpgradeTasksController * deferredUpgradeTasksController;
@property char hostsOnlyXcode3Project;
@property char hostsOnlyPackages;
@property char hostsOnlyPlayground;
@property (readonly) char shouldShowSwiftDeprecationWarning;
@property (copy) NSDate * icloudDriveLastHeldDate;
@property char hostsOnlyWrappedContainer;
@property (nonatomic) char isPotentiallyClosing;
@property (retain) NSObject<IDEWorkspaceDelegate> * workspaceDelegate;
@property (retain) NSObject<IDEActiveRunContextStoring> * activeRunContextStore;
@property (readonly) NSString * name;
@property (readonly) NSMutableSet * referencedContainers;
@property (readonly) NSSet * referencedBlueprintProviders;
@property (readonly) NSMutableSet * referencedBlueprints;
@property (readonly) NSSet * referencedSourcePackages;
@property char isWaitingForSourcePackages;
@property (copy) NSArray * sourcePackageLoadingErrors;
@property (copy) IDEActivityLogSection * sourcePackageResolutionIssueLog;
@property (readonly) NSMutableSet * customDataStores;
@property (readonly) NSArray * notificationPayloadFileReferences;
@property (readonly) IDELogManager * logManager;
@property (readonly) IDEIssueManager * issueManager;
@property (readonly) IDETextFragmentIndex * textFragmentIndex;
@property (readonly) IDERefactoring * refactoring;
@property (readonly) IDELocalizationManager * localizationManager;
@property (readonly) NSObject<IDEBuildSystemServiceProvider> * buildSystemServiceProvider;
@property (readonly) _TtC13IDEFoundation30IDEStructureEditingCoordinator * structureEditingMoveCoordinator;
@property (nonatomic) char wasLoadedForUIContext;
@property (retain,nonatomic) NSNumber * shouldUseLegacyBuildSystem;
@property (readonly) char usesModernBuildSystem;
@property (readonly) char wantsModernBuildSystem;
@property (readonly) char supportsSourcePackages;
//@property (readonly) NSSet * referencedRunnableBuildableProducts;
@property (readonly,nonatomic) char postLoadingPerformanceMetricsAllowed;
@property (readonly) DVTFilePath * wrappedContainerPath;
@property (readonly,getter=isSimpleFilesFocused) char simpleFilesFocused;
@property (readonly) NSString * representingTitle;
@property (readonly) DVTFilePath * representingFilePath;
@property (readonly) IDEContainer<IDECustomDataStoring> * representingCustomDataStore;
@property (readonly) IDEActivityLogMessage * swiftDeprecationLogMessage;
@property char isCleaningBuildFolder;
//@property (readonly) unsigned long long hash;
//@property (readonly) Class superclass;
//@property (readonly,copy) NSString * description;
//@property (readonly,copy) NSString * debugDescription;
@property (readonly) char isCancelling;
@property (readonly,nonatomic,getter=isValid) char valid;
@property (readonly) DVTStackBacktrace * invalidationBacktrace;
@property (retain) DVTStackBacktrace * creationBacktrace;
@property (readonly) IDEActivityLogSection * issueLog;
@property (readonly,nonatomic) NSSet * provisionables;
@property (readonly,nonatomic) NSSet * provisionableDevices;
+ (id)createGlobalScopeStore;
+ (id)globalScopeStore;
+ (void)initialize;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)v1;
+ (char)automaticallyNotifiesObserversOfFileRefsWithContainerLoadingIssues;
+ (id)rootElementName;
+ (id)xmlArchiveFileName;
+ (id)containerFileDataType;
+ (id)containerTypeDisplayName;
+ (id)_workspaceFileExtension;
+ (id)keyPathsForValuesAffectingReferencedSourcePackages;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingRepresentingFilePath;
+ (id)keyPathsForValuesAffectingRepresentingTitle;
+ (id)keyPathsForValuesAffectingHostsOnlyXcode3Project;
+ (id)keyPathsForValuesAffectingHostsOnlyPlayground;
+ (id)keyPathsForValuesAffectingRepresentingCustomDataStore;
+ (char)_shouldTrackReadOnlyStatus;
+ (id)keyPathsForValuesAffectingProvisionables;
+ (id)keyPathsForValuesAffectingProvisionableDevices;
- (id)ideIndex_buildParametersForIndexingBlueprint:(id)v1 synthesizedMacroOverrides:(id)v2;
- (id)ideIndex_bestSchemeForBlueprint:(id)v1;
- (id)ideIndex_runDestinationForIndexingWithScheme:(id)v1;
- (id)ideIndex_configurationNameForIndexingBlueprint:(id)v1 scheme:(id)v2;
- (id)ideModelObjectTypeIdentifier;
- (id)latestSourcePackageVersionFromTags:(id)v1;
- (id)beginSourcePackagePreflightResolutionWithReference:(id)v1 delegate:(id)v2 error:(id *)v3;
- (void)endSourcePackagePreflightResolution:(id)v1;
- (id)localScopeStore;
//- (id)newScriptingObjectOfClass:(Class)v1 forValueForKey:(id)v2 withContentsValue:(id)v3 properties:(id)v4;
- (id)sdefSupport_schemesForDocument:(id)v1;
- (id)sdefSupport_activeSchemeForDocument:(id)v1;
- (void)setSdefSupport_activeScheme:(id)v1;
- (id)_disambiguatedRunDestinations;
- (id)sdefSupport_runDestinationsForDocument:(id)v1;
- (id)sdefSupport_activeRunDestinationForDocument:(id)v1;
- (void)setSdefSupport_activeRunDestination:(id)v1;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)v1 version:(id)v2;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)v1 version:(id)v2;
- (id)_openingPerformanceMetricIdentifier;
- (void)_addPendingReferencedFileReference:(id)v1;
- (void)_removePendingReferencedFileReference:(id)v1;
- (void)_addPendingReferencedContainerPath:(id)v1;
- (void)_removePendingReferencedContainerPath:(id)v1;
- (void)_clearPendingFileReferencesAndContainerLoadingTokens;
- (void)_handleContainerResolutionFailureForFileReference:(id)v1;
- (void)_setFileRefsWithContainerLoadingIssues:(id)v1;
- (void)analyzeModelForIssues;
- (void)holdOnDiskFilesForICloudDriveIfNecessary;
- (char)_shouldLoadUISubsystems;
- (void)_setupWorkspaceArenaIfNeeded;
- (void)_finishLoadingAsynchronously:(char)v1 shouldUpgradeFromSimpleFilesFocused:(char)v2;
- (void)_checkIfHasFinishedLoading;
- (void)_containerDidLoad;
- (void)_buildProductsLocationDidChange;
- (id)initWithFilePath:(id)v1 extension:(id)v2 workspace:(id)v3 options:(id)v4 error:(id *)v5;
- (void)_setWrappedContainerPath:(id)v1;
- (id)_wrappedPlaygroundContainer;
- (char)isWrappedContainerKindOfClass:(Class)v1;
- (char)wrappedContainerConformsToProtocol:(id)v1;
- (id)_wrappingContainerPath;
- (char)_configureWrappedWorkspaceWithError:(id *)v1;
- (void)_changeContainerFilePath:(id)v1 inContext:(id)v2;
- (void)_changeContainerFilePath:(id)v1 inContext:(id)v2 upgradeToWorkspace:(char)v3;
- (char)_setContainerFilePath:(id)v1 upgradeToWorkspace:(char)v2 error:(id *)v3;
- (char)setContainerFilePath:(id)v1 error:(id *)v2;
- (void)_setupBuildCompletedNotificationForExecutionEnvironment:(id)v1 completionBlock:(void (^ /* unknown block signature */)(void))v2;
- (char)_cancelOngoingBuildWithCompletionBlockIfNeeded:(void (^ /* unknown block signature */)(void))v1;
- (id)registerClientWithName:(id)v1 promptForCancellation:(char)v2 terminationSignpost:(void (^ /* unknown block signature */)(void))v3 cancellationBlock:(void (^ /* unknown block signature */)(void))v4;
- (id)registerUncancellableClientWithName:(id)v1 terminationSignpost:(void (^ /* unknown block signature */)(void))v2;
- (id)clientsRequiringCancellationPrompt;
- (id)clientsNotSupportingCancellation;
- (void)cancelTrackedClients;
- (void)_setFileRefsForProblem8727051:(id)v1;
- (void)_processFileReferencesForProblem8727051;
- (id)_Problem9887530_wrappedContainerFileReferences:(id)v1 forPath:(id)v2;
- (id)_Problem9887530_preferredStructurePathsForContainerToContainerFileReferences:(id)v1;
- (id)_Problem9887530_preferredStructurePaths;
- (id)_Problem9887530_preferredStructurePathForContainerAtPath:(id)v1;
- (void)_addBlueprintProviderToOrderedSet:(id)v1;
- (void)_setupContainerQueries;
- (void)_setupHeaderMapPath;
- (id)buildableProductsForProductName:(id)v1;
- (id)buildableProductsForProductWithModuleName:(id)v1;
- (void)_referencedBlueprintsDidUpdateForProvider:(id)v1;
- (void)_referencedBlueprintProvideIDEdit:(id)v1;
- (void)invokeChangingValueForKey:(id)v1 fromSet:(id)v2 toSet:(id)v3 block:(void (^ /* unknown block signature */)(void))v4;
- (void)_referencedContainersDidUpdate;
- (id)containerGraphOrderForBlueprintProviders:(id)v1;
- (id)referencedSourcePackageForURL:(id)v1;
- (id)likelyAttachToTargetRunnableBuildableNames;
- (id)blueprintsContainingFilePaths:(id)v1;
- (void)_setupLogManagerIfNeeded;
- (void)_setupIssueManagerIfNeeded;
- (void)_invalidateBuildSystemServiceProvider;
- (id)displayName;
- (float)archiveVersion;
- (float)maxSupportedArchiveVersion;
- (id)_subitemsForUnarchivedSubitems:(id)v1;
- (void)_setupExecutionEnvironment;
- (void)_primitiveSetSimpleFilesFocused:(char)v1;
- (void)_setSimpleFilesFocused:(char)v1;
- (void)_setWrappedContainer:(id)v1;
- (void)_updateWrappedContainer;
- (void)primitiveInvalidate;
- (void)_handleIndexableSourcesChange:(id)v1;
- (void)_scheduleIndexingAndRefactoringRestart;
- (void)_restartIndexingAndRefactoring;
- (void)tearDownIndexAndRefactoring;
- (void)_setupDeviceInstallWorkspaceMonitor;
- (void)_setupProvisioningWorkspaceMonitor;
- (void)_initializeSourceControlWorkspaceMonitor;
- (void)_setupSourceControlWorkspaceMonitorIfNeeded;
- (void)_setupWorkspaceUpgradeTasksController;
- (void)_scheduleWorkspaceUpgradeTasksController:(id)v1;
- (void)initializeIndexAndRefactoring;
- (void)didCreateIndex:(id)v1;
- (void)_handleIndexablesChange:(id)v1;
- (id)buildableProductsForBaseName:(id)v1;
- (void)notifyBuildSystemServiceProviderThatBlueprintProviderDidChange:(id)v1;
//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
